[build]
base = "frontend"
publish = "dist"
command = "npm run build"

[build.environment]
# Optional: define environment variables here or in Netlify dashboard
# Example:
# VITE_API_BASE_URL = "https://your-backend.onrender.com"
