services:
  - type: web
    name: sentinel-os-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: OPENCAGE_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-domain.netlify.app
    healthCheckPath: /health 